version: "2.0"
services:
    mongo:
        image: mongo
        networks:
            net1:
                ipv4_address: 192.188.2.10
    amf:
        build: amf
        depends_on:
            - mongo
        networks:
            net1:
                ipv4_address: 192.188.2.2
    upf:
        build: upf
        privileged: true
        depends_on:
            - mongo
        networks:
            net1:
                ipv4_address: 192.188.2.6
            net2:
                ipv4_address: 45.45.0.2
    smf:
        build: smf
        depends_on:
            - mongo
            - upf
        networks:
            net1:
                ipv4_address: 192.188.2.4
    hss:
        build: hss
        depends_on:
            - mongo
        networks:
            net1:
                ipv4_address: 192.188.2.3
    pcrf:
        build: pcrf
        depends_on:
            - mongo
            - smf
        networks:
            net1:
                ipv4_address: 192.188.2.5
    webapp:
        build: webapp
        ports:
            - 3000:3000
        environment:
            - DB_URI=mongodb://192.188.2.10:27017/free5gc
        depends_on:
            - mongo
        networks:
            net1:
                ipv4_address: 192.188.2.11
    enb:
        build: srsLTE
        depends_on:
            - upf
            - smf
            - amf
        privileged: true
        volumes:
            - /dev/bus/usb:/dev/bus/usb
        networks:
            net1:
                ipv4_address: 192.188.2.253
networks:
    net1:
        ipam:
            driver: default
            config:
                - subnet: 192.188.2.0/24
    net2:
        ipam:
            driver: default
            config:
                - subnet: "45.45.0.0/24"
